/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'source' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@10.3.1 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_FreeRTOS        /* CMSIS-RTOS2 FreeRTOS */
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@10.3.1 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2  /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@10.3.1 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Coroutines@10.3.1 */
#define RTE_RTOS_FreeRTOS_COROUTINE     /* RTOS FreeRTOS Co-routines */
/* ARM::RTOS&FreeRTOS:Event Groups@10.3.1 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@10.3.1 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Message Buffer@10.3.1 */
#define RTE_RTOS_FreeRTOS_MESSAGE_BUFFER /* RTOS FreeRTOS Message Buffers */
/* ARM::RTOS&FreeRTOS:Stream Buffer@10.3.1 */
#define RTE_RTOS_FreeRTOS_STREAM_BUFFER /* RTOS FreeRTOS Stream Buffers */
/* ARM::RTOS&FreeRTOS:Timers@10.3.1 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* Keil::Device:StdPeriph Drivers:EXTI@3.6.0 */
#define RTE_DEVICE_STDPERIPH_EXTI
/* Keil::Device:StdPeriph Drivers:Framework@3.6.0 */
#define RTE_DEVICE_STDPERIPH_FRAMEWORK
/* Keil::Device:StdPeriph Drivers:GPIO@3.6.0 */
#define RTE_DEVICE_STDPERIPH_GPIO
/* Keil::Device:StdPeriph Drivers:RCC@3.6.0 */
#define RTE_DEVICE_STDPERIPH_RCC
/* Keil::Device:StdPeriph Drivers:TIM@3.6.0 */
#define RTE_DEVICE_STDPERIPH_TIM


#endif /* RTE_COMPONENTS_H */
